# Generated by Django 4.2.2 on 2024-06-12 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('alias', models.CharField(blank=True, max_length=120, null=True, verbose_name='Local alias')),
                ('language', models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English')], default='spanish', max_length=20, verbose_name='Language')),
                ('active', models.BooleanField(default=True)),
                ('membership', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('florida', 'Florida'), ('texas', 'Texas'), ('other', 'Other')], default='texas', max_length=20)),
                ('other_state', models.CharField(blank=True, max_length=20, verbose_name='State')),
                ('city', models.CharField(choices=[('houston', 'Houston'), ('dallas', 'Dallas'), ('austin', 'Austin'), ('san_antonio', 'San Antonio'), ('miami', 'Miami'), ('tampa', 'Tampa'), ('orlando', 'Orlando'), ('jacksonville', 'Jacksonville'), ('other', 'Other')], default='houston', max_length=20)),
                ('other_city', models.CharField(blank=True, max_length=20, verbose_name='City')),
                ('note', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, upload_to='images/avatars/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US', unique=True)),
                ('type', models.CharField(choices=[('client', 'Client'), ('provider', 'provider')], default='client', max_length=20)),
                ('license', models.CharField(blank=True, max_length=50, null=True)),
                ('outsource', models.BooleanField(default=False, verbose_name='Outsource')),
                ('debt', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('alias', models.CharField(blank=True, max_length=120, null=True, verbose_name='Local alias')),
                ('language', models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English')], default='spanish', max_length=20, verbose_name='Language')),
                ('active', models.BooleanField(default=True)),
                ('membership', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('florida', 'Florida'), ('texas', 'Texas'), ('other', 'Other')], default='texas', max_length=20)),
                ('other_state', models.CharField(blank=True, max_length=20, verbose_name='State')),
                ('city', models.CharField(choices=[('houston', 'Houston'), ('dallas', 'Dallas'), ('austin', 'Austin'), ('san_antonio', 'San Antonio'), ('miami', 'Miami'), ('tampa', 'Tampa'), ('orlando', 'Orlando'), ('jacksonville', 'Jacksonville'), ('other', 'Other')], default='houston', max_length=20)),
                ('other_city', models.CharField(blank=True, max_length=20, verbose_name='City')),
                ('note', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, upload_to='images/avatars/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US', unique=True)),
                ('vehicles', models.CharField(choices=[('1', '1'), ('2-5', '2-5'), ('>5', '>5')], default='1', max_length=20, verbose_name='Number of vehicles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='images/avatars')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Mecánico')], default=1)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='US')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
