# Generated by Django 4.1.2 on 2022-11-18 21:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, upload_to='images/avatars')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('type', models.CharField(choices=[('client', 'Client'), ('supplier', 'Supplier')], default='client', max_length=20)),
            ],
        ),
    ]
