# Generated by Django 4.1.2 on 2022-11-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_associated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associated',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatars/'),
        ),
    ]
