# Generated by Django 4.1.2 on 2022-11-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_associated_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associated',
            name='type',
            field=models.CharField(choices=[('client', 'Client'), ('provider', 'provider')], default='client', max_length=20),
        ),
    ]
