# Generated by Django 4.1.2 on 2022-12-10 18:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_associated_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, upload_to='images/avatars/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('id', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='associated',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='associated',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company'),
        ),
    ]
