# Generated by Django 4.1.2 on 2022-12-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_associated_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associated',
            name='address',
        ),
        migrations.RemoveField(
            model_name='associated',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='associated',
            name='city',
            field=models.CharField(choices=[('houston', 'Houston'), ('dallas', 'Dallas'), ('austin', 'Austin'), ('san_antonio', 'San Antonio'), ('miami', 'Miami'), ('tampa', 'Tampa'), ('orlando', 'Orlando'), ('jacksonville', 'Jacksonville'), ('other', 'Other')], default='houston', max_length=20),
        ),
        migrations.AddField(
            model_name='associated',
            name='language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English')], default='spanish', max_length=20),
        ),
        migrations.AddField(
            model_name='associated',
            name='other_state',
            field=models.CharField(blank=True, max_length=20, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='associated',
            name='state',
            field=models.CharField(choices=[('florida', 'Florida'), ('texas', 'Texas'), ('other', 'Other')], default='texas', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(choices=[('houston', 'Houston'), ('dallas', 'Dallas'), ('austin', 'Austin'), ('san_antonio', 'San Antonio'), ('miami', 'Miami'), ('tampa', 'Tampa'), ('orlando', 'Orlando'), ('jacksonville', 'Jacksonville'), ('other', 'Other')], default='houston', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English')], default='spanish', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='other_state',
            field=models.CharField(blank=True, max_length=20, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(choices=[('florida', 'Florida'), ('texas', 'Texas'), ('other', 'Other')], default='texas', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='vehicles',
            field=models.CharField(choices=[('1', '1'), ('2-5', '2-5'), ('>5', '>5')], default='1', max_length=20, verbose_name='Number of vehicles'),
        ),
    ]
