# Generated by Django 4.1.2 on 2022-12-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_associated_address_remove_associated_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associated',
            name='other_city',
            field=models.CharField(blank=True, max_length=20, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='other_city',
            field=models.CharField(blank=True, max_length=20, verbose_name='City'),
        ),
    ]
