# Generated by Django 4.1.2 on 2022-12-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_associated_other_city_company_other_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associated',
            name='language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English')], default='spanish', max_length=20, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='company',
            name='language',
            field=models.CharField(choices=[('spanish', 'Spanish'), ('english', 'English')], default='spanish', max_length=20, verbose_name='Language'),
        ),
    ]
