# Generated by Django 4.1.5 on 2023-01-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_associated_outsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='associated',
            name='alias',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Local alieas'),
        ),
    ]
