# Generated by Django 4.1.5 on 2023-01-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_company_alias_alter_associated_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='associated',
            name='membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='membership',
            field=models.BooleanField(default=False),
        ),
    ]
