# Generated by Django 4.2.2 on 2024-01-03 22:14
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_associated_debt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associated",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, unique=True
            ),
        ),
    ]
