# Generated by Django 4.2.2 on 2024-03-25 19:30
import phonenumber_field.modelfields
from django.db import migrations


def unique_phone_number(model):
    for m in model.objects.all():
        if model.objects.filter(phone_number=m.phone_number).exclude(id=m.id).exists():
            m.phone_number = None
            m.save()


def associated_unique_phone_number(apps, schema_editor):
    Associated = apps.get_model("users", "Associated")
    unique_phone_number(Associated)


def company_unique_phone_number(apps, schema_editor):
    Company = apps.get_model("users", "Company")
    unique_phone_number(Company)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_associated_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associated",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="US"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="US"
            ),
        ),
        migrations.RunPython(associated_unique_phone_number),
        migrations.RunPython(company_unique_phone_number),
    ]
