# Generated by Django 4.1.2 on 2022-10-14 01:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, upload_to='images/avatars')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('type', models.CharField(choices=[('client', 'Client'), ('supplier', 'Supplier')], default='client', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sell', 'Sell'), ('purchase', 'Purchase')], default='purchase', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approved', 'Approved'), ('processing', 'Processing'), ('complete', 'Complete')], max_length=20)),
                ('concept', models.CharField(default='Initial', max_length=120)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.associated')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('part', 'Part'), ('consumable', 'Consumable')], max_length=20)),
                ('sell_price', models.FloatField()),
                ('sell_tax', models.FloatField()),
                ('sell_price_min', models.FloatField()),
                ('sell_price_max', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='images/products')),
                ('quantity', models.FloatField()),
                ('quantity_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('factor', models.FloatField(default=1)),
                ('type', models.CharField(choices=[('mass', 'Mass'), ('count', 'Count'), ('distance', 'Distance'), ('volume', 'Volume')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=500)),
                ('tax', models.FloatField()),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.unit')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.unit'),
        ),
    ]
