# Generated by Django 4.1.2 on 2022-10-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_type_unit_magnitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_tax',
            field=models.FloatField(default=0),
        ),
    ]
