# Generated by Django 4.1.2 on 2022-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/icons'),
        ),
    ]
