# Generated by Django 4.1.2 on 2022-11-10 13:34

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associated',
            name='avatar',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='images/avatars'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='images/icons'),
        ),
    ]
