# Generated by Django 4.1.2 on 2022-11-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_associated_avatar_alter_productcategory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price_min',
        ),
        migrations.AddField(
            model_name='product',
            name='max_price',
            field=models.FloatField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='product',
            name='suggested_price',
            field=models.FloatField(blank=True, default=30),
        ),
    ]
