# Generated by Django 4.2.2 on 2024-04-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
