# Generated by Django 4.2.2 on 2024-04-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100)),
                ('var_name', models.CharField(max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vars', to='template_admin.template')),
            ],
        ),
    ]
