# Generated by Django 4.2.2 on 2024-04-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_admin', '0002_templatevars'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatevars',
            name='type',
            field=models.CharField(choices=[('STR', 'STR'), ('DATE', 'DATE'), ('INT', 'INT'), ('FLOAT', 'FLOAT')], max_length=30, null=True),
        ),
    ]
