# Generated by Django 4.2.2 on 2024-04-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_admin', '0003_templatevars_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateVars',
        ),
    ]
