# Generated by Django 4.2.2 on 2024-04-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_admin', '0004_delete_templatevars'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='tmp_type',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
