# Generated by Django 4.2.2 on 2024-04-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_admin', '0005_template_tmp_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('tmp_type', models.CharField(default='text', max_length=20)),
            ],
        ),
    ]
