# Generated by Django 4.2.2 on 2024-04-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_admin', '0006_templateversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='template_admin.templateversion')),
            ],
        ),
    ]
