# Generated by Django 4.2.2 on 2024-05-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_admin', '0007_templatecontentversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVersionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='template_admin.templateversion')),
            ],
        ),
    ]
