# Generated by Django 4.2.2 on 2024-05-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_admin', '0008_templateversionconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateversionconfig',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='template_admin.templatecontentversion'),
        ),
    ]
