# Generated by Django 4.2.2 on 2024-05-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_admin', '0009_alter_templateversionconfig_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateversion',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
