# Generated by Django 3.2.19 on 2023-06-27 17:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('imei', models.IntegerField()),
                ('device_password', models.CharField(default='123456', max_length=15)),
                ('device_id', models.IntegerField(blank=True)),
                ('Mode', models.IntegerField(choices=[(0, 'Keepalived'), (1, 'Tracking')], default=0)),
                ('Tint', models.IntegerField(default=60)),
                ('TGPS', models.IntegerField(default=5)),
                ('Tsend', models.IntegerField(default=3)),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.trailer')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('charging', models.BooleanField(blank=True, null=True)),
                ('battery', models.FloatField(blank=True, null=True)),
                ('wur', models.IntegerField(blank=True, null=True)),
                ('wdgc', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('LTE', 'Radio base'), ('GPS', 'GPS data')], default='LTE', max_length=3)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('mcc', models.IntegerField(blank=True, null=True)),
                ('mnc', models.IntegerField(blank=True, null=True)),
                ('lac', models.IntegerField(blank=True, null=True)),
                ('cellid', models.IntegerField(blank=True, null=True)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_upload', to='rent.tracker')),
            ],
        ),
    ]
