# Generated by Django 4.1.5 on 2023-07-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_manufacturer_remove_trailer_image_trailerpicture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailerpicture',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
