# Generated by Django 4.1.5 on 2023-07-07 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_trailerpicture_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/trailer')),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('XLS', 'XLS'), ('IMG', 'IMG'), ('BIN', 'BIN')], max_length=3)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('remainder_days', models.IntegerField(blank=True, choices=[(1, '1 day'), (7, '1 week'), (30, '1 month')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remainder_date', models.DateField(blank=True, null=True)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rent.trailer')),
            ],
        ),
    ]
