# Generated by Django 4.2.2 on 2023-07-24 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_associated_debt'),
        ('rent', '0005_trailerdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='LesseeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_number', models.CharField(blank=True, max_length=150)),
                ('insurance_file', models.FileField(upload_to='rental/insurances')),
                ('license_number', models.CharField(blank=True, max_length=150)),
                ('license_file', models.FileField(upload_to='rental/licenses')),
                ('associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_writing', to='users.associated')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('signed', 'Signed'), ('ready', 'Ready to sign'), ('missing', 'Missing data')], max_length=10)),
                ('location', models.CharField(max_length=500)),
                ('location_file', models.FileField(blank=True, upload_to='rental/locations')),
                ('effective_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('number_of_payments', models.IntegerField()),
                ('payment_amount', models.IntegerField()),
                ('service_charge', models.IntegerField()),
                ('security_deposit', models.IntegerField()),
                ('inspection_date', models.DateField()),
                ('current_condition', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Like new'), (3, 'Used')], default=1)),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='users.associated')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_trailer', to='rent.trailer')),
            ],
            options={
                'ordering': ('-effective_date',),
            },
        ),
        migrations.CreateModel(
            name='HandWriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='rental/signatures')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hand_writing', to='rent.lease')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='rental/contracts')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_document', to='rent.lease')),
            ],
        ),
    ]
