# Generated by Django 4.2.2 on 2023-07-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_lesseedata_lease_handwriting_contractdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='location',
            field=models.TextField(),
        ),
    ]
