# Generated by Django 4.2.2 on 2023-08-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_alter_lease_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='location_file',
        ),
        migrations.AddField(
            model_name='lease',
            name='client_id',
            field=models.ImageField(blank=True, upload_to='rental/ids'),
        ),
    ]
