# Generated by Django 4.2.2 on 2023-08-14 16:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_remove_lease_location_file_lease_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lease',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
