# Generated by Django 4.2.2 on 2023-08-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_alter_trailer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='type',
            field=models.CharField(choices=[('flatbed', 'Flatbed'), ('6_car', '6-Car'), ('3_car_w', '3-Car Wedge'), ('3_car_l', '3-Car Low profile'), ('3_car_f', '3-Car Flatbed'), ('mini5', 'Mini-5'), ('lowboy', 'Lowboy'), ('ez4', 'EZ-4'), ('other', 'Other')], max_length=20),
        ),
    ]
