# Generated by Django 4.2.2 on 2023-08-18 02:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_alter_trailer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('number_of_main_tires', models.IntegerField(choices=[(4, '4'), (6, '6'), (8, '8')])),
                ('number_of_spare_tires', models.IntegerField()),
                ('winche', models.BooleanField(default=False)),
                ('megaramp', models.BooleanField(default=False)),
                ('ramp', models.IntegerField(blank=True, choices=[(None, 'None'), (6, "6'"), (8, "8'"), (10, "10'")], null=True)),
                ('ramp_material', models.CharField(choices=[('aluminum', 'Aluminum'), ('steel', 'Steel')], default='steel', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('ancillary_battery', models.IntegerField(default=0)),
                ('strap_4inch', models.IntegerField(default=0)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.lease')),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('type', models.CharField(choices=[('spare', 'Spare'), ('main', 'Main')], max_length=10)),
                ('remaining_life', models.IntegerField(choices=[(50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=100)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.inspection')),
            ],
        ),
    ]
