# Generated by Django 4.2.2 on 2023-08-21 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_associated_debt'),
        ('rent', '0012_inspection_tire'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM rent_handwriting;"),
        migrations.AddField(
            model_name='lesseedata',
            name='client_id',
            field=models.ImageField(blank=True, upload_to='rental/ids'),
        ),
        migrations.AddField(
            model_name='lesseedata',
            name='contact_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesseedata',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                default='', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesseedata',
            name='associated',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='users.associated'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), (
                    'signed', 'Signed'), ('ready', 'Ready to sign'), ('missing', 'Missing data')], max_length=10)),
                ('trailer_location', models.TextField()),
                ('effective_date', models.DateField()),
                ('payment_amount', models.IntegerField()),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Weekly'), (
                    'biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('contract_term', models.IntegerField(default=7)),
                ('security_deposit', models.IntegerField()),
                ('lessee', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='users.associated')),
                ('trailer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='rent.trailer')),
                ('user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-effective_date',),
            },
        ),
        migrations.AlterField(
            model_name='contractdocument',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='contract_document', to='rent.contract'),
        ),
        migrations.AlterField(
            model_name='handwriting',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='hand_writing', to='rent.contract'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='lease',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='rent.contract'),
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
    ]
