# Generated by Django 4.2.2 on 2023-08-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0014_contract_delayed_payments_contract_ended_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesseedata',
            name='insurance_file',
            field=models.FileField(blank=True, upload_to='rental/insurances'),
        ),
        migrations.AlterField(
            model_name='lesseedata',
            name='insurance_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lesseedata',
            name='license_file',
            field=models.FileField(blank=True, upload_to='rental/licenses'),
        ),
        migrations.AlterField(
            model_name='lesseedata',
            name='license_number',
            field=models.CharField(max_length=150),
        ),
    ]
