# Generated by Django 4.2.2 on 2023-08-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0015_alter_lesseedata_insurance_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='service_charge',
            field=models.IntegerField(default=100),
        ),
    ]
