# Generated by Django 4.2.2 on 2023-08-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0016_contract_service_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesseedata',
            name='client_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
