# Generated by Django 4.2.2 on 2023-08-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0017_lesseedata_client_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesseedata',
            name='client_id',
        ),
        migrations.AlterField(
            model_name='lesseedata',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
