# Generated by Django 4.2.2 on 2023-08-27 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0018_remove_lesseedata_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwriting',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
