# Generated by Django 4.2.2 on 2023-09-12 22:29

from django.db import migrations, transaction
from schedule.models import Calendar
from schedule.models import Rule


def deleteCalendarData(apps, schema_editor):
    with transaction.atomic():
        cal = Calendar.objects.get(slug="rental")
        cal.delete()

        rules = Rule.objects.all()
        rules.delete()


def createCalendarData(apps, schema_editor):
    with transaction.atomic():
        # Calendar
        print("Create Rental Calendar ...")
        cal = Calendar(name="Rental Calendar", slug="rental")
        cal.save()
        print("The Rental Calendar is created.")
        # Rules
        rule = Rule(frequency="MONTHLY", name="Monthly",
                    description="will recur once every Month")
        rule.save()
        print("Monthly recurrence created")
        rule = Rule(frequency="WEEKLY", name="Biweekly",
                    params='interval:2;',
                    description="will recur once every two weeks")
        rule.save()
        print("Biweekly recurrence created")
        rule = Rule(frequency="WEEKLY", name="Weekly",
                    description="will recur once every Week")
        rule.save()
        print("Weekly recurrence created")


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('rent', '0019_handwriting_date'),
    ]

    operations = [
        migrations.RunPython(createCalendarData,
                             reverse_code=deleteCalendarData),
    ]
