# Generated by Django 4.2.2 on 2023-09-07 00:33

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0019_handwriting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwriting',
            name='img',
            field=jsignature.fields.JSignatureField(),
        ),
    ]
