# Generated by Django 4.2.2 on 2023-09-19 01:01

from django.db import migrations, models


def divide_contract_term(apps, schema_editor):
    Contract = apps.get_model('rent', 'Contract')
    for contract in Contract.objects.all():
        contract.contract_term /= 4
        contract.save()


def multiply_contract_term(apps, schema_editor):
    Contract = apps.get_model('rent', 'Contract')
    for contract in Contract.objects.all():
        contract.contract_term *= 4
        contract.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0021_lease'),
    ]

    operations = [
        migrations.RunPython(divide_contract_term,
                             reverse_code=multiply_contract_term),
        migrations.AlterField(
            model_name='contract',
            name='contract_term',
            field=models.FloatField(default=3),
        ),
    ]
