# Generated by Django 4.2.2 on 2023-09-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0022_alter_contract_contract_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='vin',
            field=models.CharField(max_length=50, unique=True, verbose_name='VIN number'),
        ),
    ]
