# Generated by Django 4.2.2 on 2023-09-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0024_payment_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remaining',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
