# Generated by Django 4.2.2 on 2023-09-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0027_due_due_date_alter_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
