# Generated by Django 4.2.2 on 2023-09-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0028_alter_due_date_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remaining',
            field=models.FloatField(default=0),
        ),
    ]
