# Generated by Django 4.2.2 on 2023-10-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0029_alter_payment_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
