# Generated by Django 4.2.2 on 2023-10-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0030_lease_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/leases')),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('XLS', 'XLS'), ('IMG', 'IMG'), ('BIN', 'BIN')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_document', to='rent.lease')),
            ],
        ),
        migrations.DeleteModel(
            name='ContractDocument',
        ),
    ]
