# Generated by Django 4.2.2 on 2023-10-06 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0031_leasedocument_delete_contractdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_deposit', to='rent.lease')),
            ],
        ),
    ]
