# Generated by Django 4.2.2 on 2023-10-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0034_trailer_active_trailer_lease_to_own'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sender_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
