# Generated by Django 4.2.2 on 2023-10-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0036_alter_lease_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='due',
            name='lease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.lease'),
        ),
    ]
