# Generated by Django 4.2.2 on 2023-10-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0038_lease_last_payment_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
