# Generated by Django 4.2.2 on 2023-11-02 19:32
from django.db import migrations, models


def initialize_remaining(apps, schema_editor):
    Lease = apps.get_model('rent', 'Lease')
    Payment = apps.get_model('rent', 'Payment')
    leases = Lease.objects.all()
    for lease in leases:
        last_payment = Payment.objects.filter(
            lease=lease).last()
        lease.remaining = last_payment.remaining
        lease.save()


class Migration(migrations.Migration):
    dependencies = [
        ('rent', '0040_contract_contract_type_contract_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='remaining',
            field=models.FloatField(default=0),
        ),
        migrations.RunPython(initialize_remaining),
    ]
