# Generated by Django 4.2.2 on 2023-11-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0041_lease_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='remaining',
        ),
    ]
