# Generated by Django 4.2.2 on 2023-11-24 13:27

from django.db import migrations, models
import django.db.models.deletion


def populate_table(apps, schema_editor):
    Trailer = apps.get_model('rent', 'trailer')
    TrailerPlates = apps.get_model('rent', 'TrailerPlates')
    db_alias = schema_editor.connection.alias
    for trailer in Trailer.objects.using(db_alias).all():
        TrailerPlates.objects.using(db_alias).create(
            plate=trailer.plate,
            trailer=trailer,
            active_plate=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0043_contract_final_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerPlates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(blank=True, max_length=50)),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('active_plate', models.BooleanField(default=False)),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rent.trailer')),
            ],
        ),
        migrations.RunPython(populate_table)
    ]
