# Generated by Django 4.2.2 on 2023-11-24 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0044_trailerplates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailerplates',
            name='trailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.trailer'),
        ),
    ]
