# Generated by Django 4.2.2 on 2023-11-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0044_rentalcostcategory_rentalcost'),
        ('rent', '0045_alter_trailerplates_trailer'),
    ]

    operations = [
    ]
