# Generated by Django 4.2.2 on 2023-12-14 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0046_merge_20231129_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDepositDevolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('returned', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.contract')),
            ],
        ),
    ]
