# Generated by Django 4.2.2 on 2023-12-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0014_use_autofields_for_pk"),
        ("rent", "0047_alter_contract_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.event",
            ),
        ),
    ]
