# Generated by Django 4.2.2 on 2023-12-17 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rent", "0048_alter_lease_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="pending_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="lease",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
