# Generated by Django 4.2.2 on 2023-12-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0048_remove_contract_final_remaining'),
        ('rent', '0048_securitydepositdevolution_returned_date'),
    ]

    operations = [
    ]
