# Generated by Django 4.2.2 on 2023-12-19 19:06

from django.db import migrations, models
import django.db.models.deletion

def populate_table(apps, schema_editor):
    LeaseDocument = apps.get_model('rent', 'leasedocument')
    db_alias = schema_editor.connection.alias
    for document in LeaseDocument.objects.using(db_alias).all():
        document.contract = document.lease.contract
        document.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0049_merge_20231218_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasedocument',
            name='contract',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rent.contract'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leasedocument',
            name='lease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_document', to='rent.lease'),
        ),
        migrations.RunPython(populate_table)
    ]
