# Generated by Django 4.2.2 on 2023-12-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0050_leasedocument_contract_alter_leasedocument_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydepositdevolution',
            name='total_deposited_amount',
            field=models.FloatField(default=0),
        ),
    ]
