# Generated by Django 4.2.2 on 2024-02-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_associated_phone_number_and_more'),
        ('rent', '0054_alter_trailer_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('amount', models.FloatField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer_deposit', to='users.associated')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailer_deposit', to='rent.trailer')),
            ],
        ),
    ]
