# Generated by Django 4.2.2 on 2024-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0055_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='document_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('DOC', 'DOC'), ('XLS', 'XLS'), ('IMG', 'IMG'), ('BIN', 'BIN')], default='BIN', max_length=3),
        ),
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/leases'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
