# Generated by Django 4.2.2 on 2024-03-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0055_trailerdeposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailerdeposit',
            name='active',
        ),
        migrations.AddField(
            model_name='trailerdeposit',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trailerdeposit',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
