# Generated by Django 4.2.2 on 2024-03-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0056_note_document_type_note_file_alter_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/notes'),
        ),
    ]
