# Generated by Django 4.2.2 on 2024-03-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0056_remove_trailerdeposit_active_and_more'),
        ('rent', '0057_alter_note_file'),
    ]

    operations = [
    ]
