# Generated by Django 4.2.2 on 2024-03-27 03:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0058_merge_20240319_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesseedata',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US'),
        ),
    ]
