# Generated by Django 4.2.2 on 2024-04-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0059_alter_lesseedata_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='template_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
