# Generated by Django 4.2.2 on 2024-04-20 13:04
from django.db import migrations

from rent.models.vehicle import Trailer


def set_trailers_pos(app, schema):
    trailers = Trailer.objects.all()
    for t in trailers:
        orders = t.get_active_order()
        order = orders.last()
        if order is not None:
            t.position = order.position
            t.position_date = (
                order.position_date
                if order.position_date is not None
                else order.created_date
            )
            if order.position == 0:
                t.position_note = "Active order: " + order.storage_reason
            else:
                t.position_note = "Active order"
            t.save()
            continue

        contracts = t.get_active_contracts()
        contract = contracts.last()
        if contract is not None:
            t.position = None
            t.position_note = "Active contract"
            t.position_date = (
                contract.updated_at
                if contract.updated_at is not None
                else contract.created_at
            )
            t.save()
            continue

        t.position = 0
        t.position_note = "Storage service"
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0060_trailer_position_trailer_position_date_and_more"),
    ]

    operations = []
