# Generated by Django 4.2.2 on 2024-04-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0060_contract_template_version'),
    ]

    operations = [
    ]
