# Generated by Django 4.2.2 on 2024-04-25 12:56
from django.db import migrations


def set_old_versions(apps, schema):
    Contract = apps.get_model("rent", "Contract")
    contracts = Contract.objects.all()
    for c in contracts:
        c.template_version = 1
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0060_contract_template_version"),
    ]

    operations = [migrations.RunPython(set_old_versions)]
