# Generated by Django 4.2.2 on 2024-04-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0061_set_old_contract_version'),
    ]

    operations = [
    ]
