# Generated by Django 4.2.2 on 2024-04-25 12:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0061_set_trailers_pos.py"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="template_version",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
