# Generated by Django 4.2.2 on 2024-05-14 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_associated_phone_number_and_more'),
        ('rent', '0062_contract_client_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guaranted_contracts', to='users.associated'),
        ),
    ]
