# Generated by Django 4.2.2 on 2024-05-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0062_trailerdeposit_days_alter_trailer_position_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerDepositTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('days', models.IntegerField(default=7)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trailer_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='rent.trailerdeposit')),
            ],
        ),
    ]
