# Generated by Django 4.2.2 on 2024-05-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0063_trailerdeposittrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailerdeposittrace',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
