# Generated by Django 4.2.2 on 2024-05-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0064_trailerdeposittrace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailerdeposit',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='rent.contract'),
        ),
    ]
