# Generated by Django 4.2.2 on 2024-05-07 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0064_contract_client_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailerdeposit',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='rent.contract'),
        ),
        migrations.AddField(
            model_name='trailerdeposit',
            name='days',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='position_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='position_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrailerDepositTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField()),
                ('days', models.IntegerField(default=7)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trailer_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='rent.trailerdeposit')),
            ],
        ),
    ]
