# Generated by Django 4.2.2 on 2024-05-09 20:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0065_trailerdeposit_contract_trailerdeposit_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasedeposit",
            name="on_hold",
            field=models.BooleanField(default=False),
        ),
    ]
