# Generated by Django 4.2.2 on 2024-05-14 19:59
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_associated_phone_number_and_more"),
        ("rent", "0066_leasedeposit_on_hold"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="guarantor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guaranted_contracts",
                to="users.associated",
            ),
        ),
    ]
