# Generated by Django 4.2.2 on 2024-05-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0068_contract_client_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasedeposit',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
