# Generated by Django 4.2.2 on 2024-05-16 16:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0070_contract_guarantor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor_name', models.CharField(max_length=120)),
                ('guarantor_license', models.CharField(max_length=50)),
                ('guarantor_address', models.CharField(max_length=500)),
                ('guarantor_email', models.EmailField(max_length=254)),
                ('guarantor_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US')),
            ],
        ),
    ]
