# Generated by Django 4.2.2 on 2024-05-18 16:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0073_contract_renovation_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitydepositdevolution",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securitydepositdevolution",
            name="reason",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
