# Generated by Django 4.2.2 on 2024-05-18 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0074_securitydepositdevolution_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('location_towit', models.BooleanField()),
                ('discount_trailer_cond', models.FloatField()),
                ('due', models.FloatField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.contract')),
            ],
        ),
    ]
