# Generated by Django 4.2.2 on 2024-05-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0075_depositdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositdiscount',
            name='discount_trailer_cond',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositdiscount',
            name='due',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositdiscount',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositdiscount',
            name='location_towit',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
