# Generated by Django 4.2.2 on 2024-05-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0076_alter_depositdiscount_discount_trailer_cond_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositdiscount',
            name='location_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
