# Generated by Django 4.2.2 on 2024-05-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0077_depositdiscount_location_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailerdeposit',
            name='template_version',
            field=models.IntegerField(default=1),
        ),
    ]
