# Generated by Django 4.2.2 on 2024-05-21 19:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0078_trailerdeposit_template_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRenovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('effective_date', models.DateField()),
                ('renovation_term', models.IntegerField(default=3)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_renovations', to='rent.contract')),
            ],
        ),
    ]
