# Generated by Django 4.2.2 on 2024-05-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0080_contract_renovation_15_notify_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositdiscount',
            name='discount_trailer_cond',
        ),
        migrations.RemoveField(
            model_name='depositdiscount',
            name='due',
        ),
        migrations.AddField(
            model_name='depositdiscount',
            name='trailer_condition_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='depositdiscount',
            name='duration',
            field=models.BooleanField(default=False),
        ),
    ]
