# Generated by Django 4.2.2 on 2024-05-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0081_remove_depositdiscount_discount_trailer_cond_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydepositdevolution',
            name='refund_date',
            field=models.DateField(null=True),
        ),
    ]
