# Generated by Django 4.2.2 on 2024-05-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0082_securitydepositdevolution_refund_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydepositdevolution',
            name='immediate_refund',
            field=models.BooleanField(default=False),
        ),
    ]
