# Generated by Django 4.2.2 on 2024-05-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0084_guarantor_guarantor_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='guarantor_license_file',
            field=models.FileField(blank=True, upload_to='rental/licenses'),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='guarantor_avatar',
            field=models.ImageField(blank=True, upload_to='images/avatars/'),
        ),
    ]
