# Generated by Django 4.2.2 on 2024-05-25 13:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0085_guarantor_guarantor_license_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesseedata',
            name='contact2_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/contact'),
        ),
        migrations.AddField(
            model_name='lesseedata',
            name='contact2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesseedata',
            name='contact2_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US'),
        ),
        migrations.AddField(
            model_name='lesseedata',
            name='contact3_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/contact'),
        ),
        migrations.AddField(
            model_name='lesseedata',
            name='contact3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesseedata',
            name='contact3_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US'),
        ),
        migrations.AddField(
            model_name='lesseedata',
            name='contact_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/contact'),
        ),
    ]
