# Generated by Django 4.2.2 on 2024-05-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0086_lesseedata_contact2_file_lesseedata_contact2_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailerdeposit',
            name='returned_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailerdeposit',
            name='returned_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
