# Generated by Django 4.2.2 on 2024-05-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0087_trailerdeposit_returned_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositdiscount',
            name='saved_duration_in_days',
            field=models.IntegerField(null=True),
        ),
    ]
