# Generated by Django 4.2.2 on 2024-06-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0088_depositdiscount_saved_duration_in_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydepositdevolution',
            name='prepayments',
            field=models.FloatField(default=0),
        ),
    ]
