# Generated by Django 4.2.2 on 2024-06-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0089_securitydepositdevolution_prepayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitydepositdevolution',
            name='debts',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='securitydepositdevolution',
            name='tolls',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='securitydepositdevolution',
            name='trailer_discount',
            field=models.FloatField(default=0),
        ),
    ]
