# Generated by Django 4.2.2 on 2024-06-04 13:05
from django.db import migrations
from django.db import models

from rent.models.deposit_discount import DepositDiscount


def set_debts_tolls_discount(apps, scheme):
    # DepositDiscount = apps.get_model("rent", "DepositDiscount")
    SecurityDepositDevolution = apps.get_model("rent", "SecurityDepositDevolution")

    discounts = DepositDiscount.objects.all()
    for dis in discounts:
        dev = SecurityDepositDevolution.objects.filter(
            contract__id=dis.contract.id
        ).last()
        if dev is None:
            continue

        dev.debts = dis.debt
        dev.tolls = dis.tolls
        dev.trailer_discount = dis.trailer_condition_discount
        dev.save()


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0090_securitydepositdevolution_debts_and_more"),
    ]

    operations = [
        migrations.RunPython(set_debts_tolls_discount),
    ]
