# Generated by Django 4.2.2 on 2024-06-04 13:05
from django.db import migrations
from django.db import models

from rent.models.deposit_discount import DepositDiscount
from rent.models.lease import SecurityDepositDevolution


def fix_security_deposit_debts(apps, scheme):
    # DepositDiscount = apps.get_model("rent", "DepositDiscount")
    devolutions = SecurityDepositDevolution.objects.all()
    for dev in devolutions:
        dev.debts = dev.income - dev.tolls - dev.trailer_discount
        dev.save()


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0091_securitydepositdevolution_set_debts_tolls_and_trailer_discount"),
    ]

    operations = [
        migrations.RunPython(fix_security_deposit_debts),
    ]
