# Generated by Django 4.2.2 on 2024-06-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0092_securitydepositdevolution_fix_debts'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositdiscount',
            name='saved_contract_exp',
            field=models.DateField(null=True),
        ),
    ]
