# Generated by Django 4.2.2 on 2024-06-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0093_depositdiscount_saved_contract_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositdiscount',
            name='security_deposit_devolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='rent.securitydepositdevolution'),
        ),
    ]
