# Generated by Django 4.2.2 on 2024-06-05 14:29
from django.db import migrations

from rent.models.deposit_discount import DepositDiscount
from rent.models.lease import SecurityDepositDevolution


def init_discount_sec_dep_dev(apps, schema):
    discounts = DepositDiscount.objects.all()
    for dis in discounts:
        sec_dev = SecurityDepositDevolution.objects.filter(contract=dis.contract).last()
        if sec_dev is None:
            continue

        dis.security_deposit_devolution = sec_dev
        dis.save()


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0094_depositdiscount_security_deposit_devolution"),
    ]

    operations = []
