# Generated by Django 4.2.2 on 2024-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0095_depositdiscount_sec_dev_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesseedata',
            name='contact_relation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
