# Generated by Django 4.2.2 on 2024-06-07 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0096_lesseedata_contact_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.contract'),
        ),
    ]
