# Generated by Django 4.2.2 on 2024-06-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0098_auto_due_contract_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpaidDues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpaid_dues', to='rent.depositdiscount')),
            ],
        ),
    ]
