# Generated by Django 4.2.2 on 2024-06-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0099_unpaiddues'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitydepositdevolution',
            old_name='tolls',
            new_name='saved_tolls',
        ),
    ]
