# Generated by Django 4.2.2 on 2024-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0100_rename_tolls_securitydepositdevolution_saved_tolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesseedata',
            name='contact2_relation',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lesseedata',
            name='contact3_relation',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
