# Generated by Django 4.2.2 on 2024-06-12 15:39
from django.db import migrations

from rent.models.lease import SecurityDepositDevolution


def fix_tolls_dynamic(apps, schema):
    devs = SecurityDepositDevolution.objects.all()
    for dev in devs:
        if dev.amount > 0:
            dev.amount = dev.amount - dev.tolls
        else:
            dev.amount = dev.amount + dev.tolls

        dev.debts = dev.total_deposited_amount - dev.amount
        dev.save()


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0101_lesseedata_contact2_relation_and_more"),
    ]

    operations = []
