# Generated by Django 4.2.2 on 2024-06-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0102_fix_saved_tolls_to_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='guarantor_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
