# Generated by Django 4.2.2 on 2024-06-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0103_contract_guarantor_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositdiscount',
            name='init_invoice_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
