# Generated by Django 4.2.2 on 2024-06-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0104_depositdiscount_init_invoice_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositdiscount',
            name='init_invoice_text',
        ),
        migrations.AddField(
            model_name='depositdiscount',
            name='init_state',
            field=models.BooleanField(null=True),
        ),
    ]
