from django.urls import path
from .views import (
    create_unit,
    create_category,
    create_product,
    create_associated,
    create_order,
    list_unit,
    list_category,
    list_product,
    list_associated,
    list_order,
    update_category,
    update_product,
    update_order,
    delete_category,
    delete_product,
    detail_order,
    detail_transaction,
    create_transaction,
    finish_order,
    select_product,
    select_new_product,
)


urlpatterns = [
    path('create-unit/', create_unit, name='create-unit'),
    path('create-associated/', create_associated, name='create-associated'),
    path('create-product/', create_product, name='create-product'),
    path('create-category/', create_category, name='create-category'),
    path('create-order/', create_order, name='create-order'),
    path('create-transaction/<order_id>/<product_id>',
         create_transaction, name='create-transaction'),
    path('list-unit/', list_unit, name='list-unit'),
    path('list-category/', list_category, name='list-category'),
    path('list-product/', list_product, name='list-product'),
    path('list-associated/', list_associated, name='list-associated'),
    path('list-order/', list_order, name='list-order'),
    path('update-category/<id>', update_category, name='update-category'),
    path('update-product/<id>', update_product, name='update-product'),
    path('update-order/<id>', update_order, name='update-order'),
    path('delete-category/<id>', delete_category, name='delete-category'),
    path('delete-product/<id>', delete_product, name='delete-product'),
    path('select-product/<next>/<order_id>',
         select_product, name='select-product'),
    path('select-new-product/<next>/<order_id>',
         select_new_product, name='select-new-product'),
    path('detail-order/<id>', detail_order, name='detail-order'),
    path('finish-order/<id>', finish_order, name='finish-order'),
    path('detail-transaction/<id>', detail_transaction, name='detail-transaction'),
]
