# Generated by Django 4.2.2 on 2024-06-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2000, '<2010'), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], verbose_name='year')),
                ('vin', models.CharField(max_length=50, verbose_name='VIN number')),
                ('note', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/equipment')),
                ('plate', models.CharField(blank=True, max_length=50)),
                ('cdl', models.BooleanField()),
                ('type', models.CharField(choices=[('flatbed', 'Flatbed'), ('3car', '3-Car Carrier'), ('mini5', 'Mini-5'), ('lowboy', 'Lowboy'), ('other', 'Other')], max_length=20)),
                ('manufacturer', models.CharField(choices=[('pj', 'PJ'), ('bigtex', 'Bigtex'), ('Load trail', 'Load Trail'), ('kaufman', 'Kaufman'), ('lamar', 'Lamar'), ('delco', 'Delco'), ('gatormade', 'Gatormade'), ('other', 'Other')], max_length=20)),
                ('axis_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='Number of axles')),
                ('load', models.IntegerField(choices=[(7, 7000), (8, 8000), (10, 10000), (12, 12000)], verbose_name='Axle load capacity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2000, '<2010'), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], verbose_name='year')),
                ('vin', models.CharField(max_length=50, verbose_name='VIN number')),
                ('note', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/equipment')),
                ('plate', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(choices=[('ram', 'RAM'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('gmc', 'GCM'), ('other', 'Other')], max_length=20)),
                ('model', models.CharField(choices=[('3500', '3500'), ('2500', '2500'), ('1500', '1500'), ('other', 'Other')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
