# Generated by Django 4.2.2 on 2024-06-12 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
        ('users', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='services/signatures')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.associated')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand_writing', to='utils.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('chartColor', models.CharField(choices=[('#696cff', 'violet'), ('#8592a3', 'gray'), ('#71dd37', 'green'), ('#ff3e1d', 'red'), ('#ffab00', 'yellow'), ('#03c3ec', 'blue'), ('#233446', 'black')], default='#8592a3', max_length=7)),
                ('icon', models.ImageField(blank=True, upload_to='images/icons')),
                ('extra_charge', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('sell_tax', models.FloatField(blank=True, default=8.25)),
                ('suggested_price', models.FloatField(blank=True)),
                ('tire', models.BooleanField(default=False)),
                ('internal', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('chartColor', models.CharField(choices=[('#696cff', 'violet'), ('#8592a3', 'gray'), ('#71dd37', 'green'), ('#ff3e1d', 'red'), ('#ffab00', 'yellow'), ('#03c3ec', 'blue'), ('#233446', 'black')], default='#8592a3', max_length=7)),
                ('icon', models.ImageField(blank=True, upload_to='images/icons')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('tax', models.FloatField(default=8.25)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/services')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_picture', to='utils.order')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory'),
        ),
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, choices=[('trailer', 'Trailer'), ('vehicle', 'Vehicle')], max_length=20, null=True)),
                ('concept', models.CharField(choices=[('Maintenance to trailer', 'Maintenance to trailer'), ('Quotation', 'Quotation'), ("Parts' sale", "Parts' sale")], default='Maintenance to trailer', max_length=120)),
                ('creating_order', models.BooleanField(default=True)),
                ('using_signature', models.BooleanField(default=False)),
                ('new_associated', models.BooleanField(default=False)),
                ('completed', models.BooleanField(null=True)),
                ('associated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.associated')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.order')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ordersignature')),
                ('trailer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.trailer')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PendingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.paymentcategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.associated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('extra_charge', models.FloatField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.paymentcategory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_payment', to='utils.order')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='images/expenses')),
                ('description', models.TextField(blank=True)),
                ('cost', models.FloatField(blank=True)),
                ('associated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.associated')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.order')),
            ],
        ),
        migrations.CreateModel(
            name='DebtStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('lost', 'Lost')], default='pending', max_length=20)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('weeks', models.PositiveIntegerField(default=0)),
                ('amount_due_per_week', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.associated')),
            ],
        ),
    ]
