# Generated by Django 4.1.2 on 2022-12-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='max_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='suggested_price',
            field=models.FloatField(blank=True),
        ),
    ]
