# Generated by Django 4.1.2 on 2022-12-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('services', '0002_alter_service_max_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceTransaction', to='utils.order'),
        ),
    ]
