# Generated by Django 4.1.2 on 2022-12-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicetransaction_quantity_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profit',
        ),
    ]
