# Generated by Django 4.1.2 on 2023-01-09 18:03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_service_image_alter_service_sell_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/expenses"),
        ),
    ]
