# Generated by Django 4.1.5 on 2023-01-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_service_image_expense_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sell_tax',
            field=models.FloatField(blank=True, default=8.25),
        ),
    ]
