# Generated by Django 4.1.5 on 2023-01-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_service_sell_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='max_price',
        ),
    ]
