# Generated by Django 4.1.2 on 2023-03-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_paymentcategory_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='exclusive',
        ),
        migrations.AddField(
            model_name='payment',
            name='extra_charge',
            field=models.FloatField(default=0),
        ),
    ]
