# Generated by Django 4.1.5 on 2023-04-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_pendingpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.paymentcategory'),
        ),
    ]
