# Generated by Django 4.2.2 on 2024-01-19 13:52
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0024_alter_order_plate"),
        ("users", "0017_alter_associated_phone_number_and_more"),
        ("services", "0023_service_internal_service_marketing_service_tire"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSignature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=50)),
                ("img", models.ImageField(upload_to="services/signatures")),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "associated",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.associated",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hand_writing",
                        to="utils.order",
                    ),
                ),
            ],
        ),
    ]
