# Generated by Django 4.2.2 on 2024-04-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_associated_phone_number_and_more'),
        ('services', '0026_ordersignature'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreorderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.associated')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ordersignature')),
            ],
        ),
    ]
