# Generated by Django 4.2.2 on 2024-04-08 20:10
from django.db import migrations


def create_preorders(apps, schema_editor):
    Associated = apps.get_model("users", "Associated")
    OrderSignature = apps.get_model("services", "OrderSignature")
    PreorderData = apps.get_model("services", "PreorderData")

    for associated in Associated.objects.all():
        sign = OrderSignature.objects.filter(associated=associated).last()
        if not PreorderData.objects.filter(
            associated=associated, signature=sign
        ).exists():
            PreorderData.objects.create(
                associated=associated,
                signature=sign,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0027_preorderdata"),
    ]

    operations = [
        migrations.RunPython(create_preorders),
    ]
