# Generated by Django 4.2.2 on 2024-04-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0033_alter_order_storage_reason'),
        ('services', '0029_preorderdata_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderdata',
            name='orders',
            field=models.ManyToManyField(related_name='preorders', to='utils.order'),
        ),
    ]
