# Generated by Django 4.2.2 on 2024-04-08 20:10
from django.db import migrations


def create_preorders(apps, schema_editor):
    PreorderData = apps.get_model("services", "PreorderData")
    apps.get_model("utils", "Order")

    for preorder in PreorderData.objects.all():
        if (
            preorder.signature is not None
            and preorder.signature.order is not None
            and not preorder.orders.filter(id=preorder.signature.order.id).exists()
        ):
            preorder.orders.add(preorder.signature.order)


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0030_preorderdata_orders"),
    ]

    operations = [
        migrations.RunPython(create_preorders),
    ]
