# Generated by Django 4.2.2 on 2024-04-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0034_alter_order_vin'),
        ('users', '0019_alter_associated_phone_number_and_more'),
        ('equipment', '0005_alter_trailer_year_alter_vehicle_year'),
        ('services', '0031_autoadd_preorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(blank=True, choices=[('trailer', 'Trailer'), ('vehicle', 'Vehicle')], max_length=20, null=True)),
                ('concept', models.CharField(choices=['Maintenance to trailer', 'Quotation', "Parts' sale"], default='Maintenance to trailer', max_length=120)),
                ('creating_order', models.BooleanField(default=True)),
                ('using_signature', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.order')),
                ('preorder_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.preorderdata')),
                ('trailer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.trailer')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.vehicle')),
            ],
        ),
    ]
