# Generated by Django 4.2.2 on 2024-04-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0059_alter_lesseedata_contact_phone'),
        ('services', '0032_preorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='trailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.trailer'),
        ),
    ]
