# Generated by Django 4.2.2 on 2024-04-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_alter_preorder_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorderdata',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='preorderdata',
            name='ready',
        ),
        migrations.AddField(
            model_name='preorder',
            name='completed',
            field=models.BooleanField(null=True),
        ),
    ]
