# Generated by Django 4.2.2 on 2024-04-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_remove_preorderdata_orders_remove_preorderdata_ready_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='concept',
            field=models.CharField(choices=[('Maintenance to trailer', 'Maintenance to trailer'), ('Quotation', 'Quotation'), ("Parts' sale", "Parts' sale")], default='Maintenance to trailer', max_length=120),
        ),
    ]
