# Generated by Django 4.2.2 on 2024-04-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_associated_phone_number_and_more'),
        ('services', '0035_alter_preorder_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='associated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.associated'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ordersignature'),
        ),
    ]
