# Generated by Django 4.2.2 on 2024-04-12 20:01
from django.db import migrations


def create_preorders(apps, schema_editor):
    Preorder = apps.get_model("services", "Preorder")

    for preorder in Preorder.objects.all():
        pd = preorder.preorder_data
        if pd is not None:
            preorder.associated = pd.associated
            preorder.signature = pd.signature
            preorder.save()


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0036_preorder_associated_preorder_signature"),
    ]

    operations = [migrations.RunPython(create_preorders)]
