# Generated by Django 4.2.2 on 2024-04-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_preorder_data_to_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='new_associated',
            field=models.BooleanField(default=False),
        ),
    ]
