# Generated by Django 4.2.2 on 2024-04-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_preorder_new_associated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='preorder_data',
        ),
    ]
