# Generated by Django 4.2.2 on 2024-04-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_remove_preorder_preorder_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreorderData',
        ),
    ]
