# Generated by Django 4.2.2 on 2024-04-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0039_order_processing_user_order_terminated_user'),
        ('services', '0040_delete_preorderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowitPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towit_service_payment', to='utils.order')),
            ],
        ),
    ]
