from menu.menu.menu_element import MenuItem


MENU = [
    # Main menu
    MenuItem(
        name="Principal",
        i18n="Analytics",
        icon="bx-home-circle",
        url="dashboard",
        exact_match=True,
    ),
    MenuItem(
        name="Reportes",
        icon="bx-stats",
        children=[
            MenuItem(
                name="MANTENIMIENTO",
                i18n="Reportes",
                children=[
                    MenuItem(
                        name="Weekly",
                        url="weekly-report",
                    ),
                    MenuItem(
                        name="Monthly",
                        url="monthly-report",
                    ),
                ],
            ),
            MenuItem(
                name="RENTA",
                i18n="Reportes",
                children=[
                    MenuItem(
                        name="Monthly",
                        url="monthly-membership",
                    ),
                ],
            ),
        ],
    ),
    MenuItem(
        name="Asociados",
        icon="bx-user-circle",
        i18n="Negocio",
        children=[
            MenuItem(
                name="Clientes",
                url="list-client",
            ),
            MenuItem(
                name="Compañías",
                i18n="Companies",
                url="list-company",
            ),
            MenuItem(
                name="Operarios",
                i18n="Usuarios",
                url="list-user",
                dj_perms=["auth.add_user"],
            ),
        ],
    ),
    # Services menu
    MenuItem("MANTENIMIENTO"),
    MenuItem(
        name="Órdenes",
        i18n="Sells",
        icon="bx-wrench",
        url="list-service-order",
    ),
    MenuItem(
        name="Storage",
        icon="bxs-car-garage",
        url="storage-view",
    ),
    MenuItem(
        name="Configuración",
        i18n="Account Settings",
        icon="bx-cog",
        dj_perms=["auth.add_user"],
        children=[
            MenuItem(
                name="Servicios",
                i18n="Usuarios",
                url="list-service",
            ),
            MenuItem(
                name="Categorías",
                i18n="Clientes",
                url="list-service-category",
            ),
            MenuItem(
                name="Pagos",
                i18n="Payments",
                url="list-payment-category",
            ),
        ],
    ),
    MenuItem(
        name="Gastos",
        i18n="Account Settings",
        icon="bx-credit-card",
        dj_perms=["auth.add_user"],
        children=[
            MenuItem(
                name="Gastos",
                i18n="Sells",
                url="list-cost",
            ),
            MenuItem(
                name="Categorías",
                i18n="Clientes",
                url="list-costs-category",
            ),
        ],
    ),
    # Rent menu
    MenuItem("RENTA"),
    MenuItem(
        name="Lessees",
        i18n="Sells",
        icon="bx-user",
        url="client-list",
    ),
    MenuItem(
        name="Trailers",
        i18n="Sells",
        icon="bx-traffic-cone",
        url="list-trailer",
    ),
    MenuItem(
        name="Configuración",
        i18n="Account Settings",
        icon="bx-cog",
        dj_perms=["auth.add_user"],
        children=[
            MenuItem(
                name="Tolls",
                icon="bx-traffic-cone",
                url="list-toll",
            ),
            MenuItem(
                name="Trackers",
                icon="bx-location-plus",
                url="trackers-table",
            ),
            MenuItem(
                name="Gastos",
                i18n="Account Settings",
                icon="bx-credit-card",
                children=[
                    MenuItem(
                        name="Gastos",
                        i18n="Sells",
                        url="list-cost-rental",
                    ),
                    MenuItem(
                        name="Categorías",
                        i18n="Clientes",
                        url="list-costs-rental-category",
                    ),
                ],
            ),
        ],
    ),
    # Inventary menu
    MenuItem("INVENTARIO", dj_perms=["auth.add_user"]),
    MenuItem(
        name="Productos",
        i18n="Inventario",
        icon="bx-collection",
        url="list-product",
        dj_perms=["auth.add_user"],
    ),
    MenuItem(
        name="Configuración",
        i18n="Account Settings",
        icon="bx-cog",
        dj_perms=["auth.add_user"],
        children=[
            MenuItem(
                name="Kits",
                i18n="Inventario",
                url="list-kit",
            ),
            MenuItem(
                name="Precios",
                url="minprice-product",
            ),
            MenuItem(
                name="Categorías",
                url="list-category",
            ),
            MenuItem(
                name="Unidades",
                url="list-unit",
            ),
        ],
    ),
    MenuItem(
        name="Compras",
        i18n="Account Settings",
        icon="bx-store",
        children=[
            MenuItem(
                name="Órdenes",
                i18n="Purchases",
                url="list-order",
            ),
            MenuItem(
                name="Proveedores",
                url="list-provider",
            ),
        ],
    ),
]


def getMenuCtx(request):
    return {"MenuItems": MENU}
