# Generated by Django 4.1.2 on 2022-10-14 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='type',
            new_name='magnitude',
        ),
    ]
