# Generated by Django 4.1.2 on 2022-10-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_order_created_date_alter_order_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField()),
                ('cost', models.FloatField()),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField()),
                ('profit', models.FloatField()),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
