# Generated by Django 4.1.2 on 2022-11-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_associated'),
        ('inventory', '0013_remove_product_image_remove_product_sell_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='associated',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='users.associated'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_tax',
            field=models.FloatField(blank=True, default=8.25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax',
            field=models.FloatField(default=8.25),
        ),
        migrations.DeleteModel(
            name='Associated',
        ),
    ]
