# Generated by Django 4.1.2 on 2022-12-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_order_associated_alter_product_sell_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='associated',
        ),
    ]
