# Generated by Django 4.1.2 on 2022-12-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_transaction_order'),
        ('inventory', '0015_remove_order_associated'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.order'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
