# Generated by Django 4.1.2 on 2022-12-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        ('inventory', '0016_alter_transaction_order_delete_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='ProductTransaction',
        ),
    ]
