# Generated by Django 4.1.2 on 2022-12-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
