# Generated by Django 4.1.2 on 2022-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_producttransaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Profit',
        ),
    ]
