# Generated by Django 4.1.2 on 2022-12-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_producttransaction_cost_delete_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='max_price',
            new_name='min_price',
        ),
    ]
