# Generated by Django 4.1.2 on 2022-12-19 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_product_type_pricereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricereference',
            name='updated_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
