# Generated by Django 4.1.2 on 2022-12-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_pricereference_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricereference',
            name='updated_date',
            field=models.DateField(),
        ),
    ]
