# Generated by Django 4.1.2 on 2023-02-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_productkit_kitelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitelement',
            name='quantity',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='kitelement',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.unit'),
            preserve_default=False,
        ),
    ]
