# Generated by Django 4.1.2 on 2023-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_kitelement_quantity_kitelement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitelement',
            name='quantity',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
