# Generated by Django 4.1.5 on 2023-04-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_kitservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='chartColor',
            field=models.CharField(default='#8592a3', max_length=7),
        ),
    ]
