# Generated by Django 4.2.2 on 2024-05-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_custom_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='done',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
