# Generated by Django 4.2.2 on 2024-05-02 13:18
from django.db import migrations


def set_done_state(app, schema):
    ProductTransaction = app.get_model("inventory", "ProductTransaction")
    trans = ProductTransaction.objects.filter(order__status="complete")
    for t in trans:
        t.done = True
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_producttransaction_done"),
    ]

    operations = [migrations.RunPython(set_done_state)]
