# Generated by Django 4.2.2 on 2024-05-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_set_product_trans_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='decline',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
