# Generated by Django 4.2.2 on 2024-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_producttransaction_decline'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttransaction',
            name='active_tax',
            field=models.BooleanField(default=True),
        ),
    ]
