# Generated by Django 4.2.2 on 2024-06-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_producttransaction_active_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransactionStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_refs', to='inventory.stock')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_refs', to='inventory.producttransaction')),
            ],
        ),
    ]
