# Generated by Django 4.1.2 on 2023-01-05 18:29

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_alter_cost_related_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='file',
        ),
        migrations.AddField(
            model_name='cost',
            name='image',
            field=models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='images/costs'),
        ),
    ]
