# Generated by Django 4.1.5 on 2023-04-10 14:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("costs", "0002_alter_cost_related_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="costcategory",
            name="chartColor",
            field=models.CharField(default="#8592a3", max_length=7),
        ),
    ]
