# Generated by Django 4.1.5 on 2023-04-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_remove_cost_file_cost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcategory',
            name='chartColor',
            field=models.CharField(default='#8592a3', max_length=7),
        ),
    ]
