# Generated by Django 4.2.2 on 2023-11-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0005_alter_costcategory_chartcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/costs'),
        ),
    ]
