# Generated by Django 4.2.2 on 2024-05-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="twiliocall",
            name="api_version",
        ),
        migrations.RemoveField(
            model_name="twiliocall",
            name="called",
        ),
        migrations.RemoveField(
            model_name="twiliocall",
            name="called_zip",
        ),
        migrations.RemoveField(
            model_name="twiliocall",
            name="caller_zip",
        ),
        migrations.RemoveField(
            model_name="twiliocall",
            name="from_zip",
        ),
        migrations.RemoveField(
            model_name="twiliocall",
            name="to_zip",
        ),
    ]
