# Generated by Django 4.2.2 on 2024-05-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_associated_phone_number_and_more"),
        ("crm", "0002_remove_twiliocall_api_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="twiliocall",
            name="associated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.associated",
            ),
        ),
    ]
