# Generated by Django 4.2.2 on 2024-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_twiliocall_associated"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlaggedCalls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("BL", "Añadir a lista negra"),
                            ("PL", "Añadir a lista de llamadas personal"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SP", "Número de spam/llamadas molestas"),
                            ("PC", "Llamada personal"),
                            ("OT", "Otro motivo"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
