# Generated by Django 4.2.2 on 2024-06-12 18:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sell', 'Sell'), ('purchase', 'Purchase')], default='purchase', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approved', 'Approved'), ('processing', 'Processing'), ('payment_pending', 'Payment pending'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('concept', models.CharField(default='Initial', max_length=120)),
                ('note', models.TextField(blank=True)),
                ('position', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('position_date', models.DateTimeField(null=True)),
                ('invoice_data', models.TextField(blank=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True)),
                ('plate', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('equipment_type', models.CharField(blank=True, choices=[('trailer', 'Trailer'), ('vehicle', 'Vehicle')], max_length=20, null=True)),
                ('terminated_date', models.DateTimeField(blank=True, null=True)),
                ('processing_date', models.DateTimeField(blank=True, null=True)),
                ('discount', models.FloatField(default=0)),
                ('quotation', models.BooleanField(default=False)),
                ('parts_sale', models.BooleanField(default=False)),
                ('invoice_sended', models.BooleanField(default=False)),
                ('storage_reason', models.CharField(blank=True, choices=[('capacity', 'Falta de capacidad en el taller'), ('approval', 'Pendiente por aprobación del cliente'), ('ready', 'Listo para recoger'), ('storage_service', 'Servicio de storage')], default='storage_service', max_length=20, null=True)),
                ('associated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.associated')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('processing_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_orders', to=settings.AUTH_USER_MODEL)),
                ('terminated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_orders', to=settings.AUTH_USER_MODEL)),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent.trailer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('incoming_date', models.DateTimeField(auto_now_add=True)),
                ('plate', models.CharField(max_length=50, unique=True)),
                ('outgoing_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('repair', 'Repair'), ('rental', 'Rental'), ('storage', 'Storage'), ('other', 'Other')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_orders', models.IntegerField(default=0)),
                ('gross_income', models.FloatField(default=0)),
                ('profit_before_costs', models.FloatField(default=0)),
                ('labor_income', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('third_party', models.FloatField(default=0)),
                ('supplies', models.FloatField(default=0)),
                ('costs', models.FloatField(default=0)),
                ('parts_cost', models.FloatField(default=0)),
                ('parts_price', models.FloatField(default=0)),
                ('payment_amount', models.FloatField(default=0)),
                ('transactions', models.IntegerField(default=0)),
                ('debt_created', models.FloatField(default=0)),
                ('debt_paid', models.FloatField(default=0)),
                ('membership_orders', models.IntegerField(default=0)),
                ('membership_amount', models.FloatField(default=0)),
                ('security_payments', models.FloatField(default=0)),
                ('returned_security_payments', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('gpt_insights', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('statistics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.statistics')),
            ],
            bases=('utils.statistics',),
        ),
        migrations.CreateModel(
            name='OrderTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trace', models.CharField(choices=[('storage_in', 'Storage in'), ('storage_out', 'Storage out'), ('storage_stage', 'Storage stage change')], max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_traces', to='utils.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDeclineReazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decline_reazon', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.order')),
            ],
        ),
    ]
