# Generated by Django 4.1.2 on 2022-12-03 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_associated_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sell', 'Sell'), ('purchase', 'Purchase')], default='purchase', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approved', 'Approved'), ('processing', 'Processing'), ('complete', 'Complete')], default='pending', max_length=20)),
                ('concept', models.CharField(default='Initial', max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('associated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.associated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
