# Generated by Django 4.1.2 on 2022-12-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='terminated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
