# Generated by Django 4.1.2 on 2022-12-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_order_terminated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='badge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
