# Generated by Django 4.1.2 on 2022-12-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_associated_address_remove_associated_company_and_more'),
        ('utils', '0004_order_trailer_order_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company'),
        ),
    ]
