# Generated by Django 4.1.2 on 2023-01-05 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_associated_language_alter_company_language'),
        ('utils', '0006_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='associated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.associated'),
        ),
    ]
