# Generated by Django 4.1.5 on 2023-01-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_alter_order_associated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='equipment_type',
            field=models.CharField(blank=True, choices=[('trailer', 'Trailer'), ('vehicle', 'Vehicle')], max_length=20, null=True),
        ),
    ]
