# Generated by Django 4.1.2 on 2023-04-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='debt_accumulated',
        ),
    ]
