# Generated by Django 4.1.5 on 2023-05-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_remove_statistics_debt_accumulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='gpt_insights',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
