# Generated by Django 4.1.5 on 2023-05-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_statistics_gpt_insights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='gpt_insights',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
