# Generated by Django 3.2.19 on 2023-06-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_alter_order_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quotation',
            field=models.BooleanField(default=False),
        ),
    ]
