# Generated by Django 4.2.2 on 2023-07-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_order_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vin',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
