# Generated by Django 4.2.2 on 2023-09-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_remove_order_badge_order_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('incoming_date', models.DateTimeField(auto_now_add=True)),
                ('plate', models.CharField(max_length=50, unique=True)),
                ('outgoing_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('repair', 'Repair'), ('rental', 'Rental'), ('other', 'Other')], max_length=50)),
                ('note', models.TextField()),
            ],
        ),
    ]
