# Generated by Django 4.2.2 on 2023-09-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_alter_plate_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
