# Generated by Django 4.2.2 on 2023-10-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0019_alter_plate_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
