# Generated by Django 4.2.2 on 2024-01-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_statistics_returned_security_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
