# Generated by Django 4.2.2 on 2024-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0023_order_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
