# Generated by Django 4.2.2 on 2024-01-22 19:34

import django.core.validators
from django.db import migrations, models


def actualizar_valores(apps, schema_editor):
    Order = apps.get_model("utils", "Order")
    for order in Order.objects.all():
        if order.status in ["processing", "pending"]:
            if order.position is None:
                order.position = 0
        else:
            order.position = None
        order.save()


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0024_alter_order_plate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="position",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
        ),
        migrations.RunPython(actualizar_valores),
    ]
