# Generated by Django 4.2.2 on 2024-01-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0025_alter_order_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trace', models.CharField(choices=[('storage_in', 'Storage in'), ('storage_out', 'Storage out'), ('storage_stage', 'Storage stage change')], max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.order')),
            ],
        ),
    ]
