# Generated by Django 4.2.2 on 2024-01-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0026_ordertrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external',
            field=models.BooleanField(default=False),
        ),
    ]
