# Generated by Django 4.2.2 on 2024-03-14 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0029_remove_order_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='storage_reason',
            field=models.CharField(blank=True, choices=[('capacity', 'Falta de capacidad en el taller'), ('approval', 'Pendiente por aprobación del cliente'), ('ready', 'Listo para recoger'), ('storage_service', 'Servicio de storage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordertrace',
            name='reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordertrace',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_traces', to='utils.order'),
        ),
    ]
