# Generated by Django 4.2.2 on 2024-04-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0029_remove_order_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
