# Generated by Django 4.2.2 on 2024-04-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0030_order_printed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='printed',
            new_name='labor_viewed',
        ),
    ]
