# Generated by Django 4.2.2 on 2024-04-06 15:13
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("utils", "0031_rename_printed_order_labor_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="processing_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processing_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="terminated_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terminated_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
