# Generated by Django 4.2.2 on 2024-03-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0031_order_decline_reazon_alter_order_storage_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='decline_reazon',
        ),
        migrations.CreateModel(
            name='OrderDeclineReazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decline_reazon', models.CharField(blank=True, choices=[('no_money', 'No tiene dinero'), ('price', 'No está de acuerdo con el precio'), ('later', 'Lo va a hacer más adelante'), ('wait', 'No puede esperar'), ('conditions', 'No está de acuerdo con los terminos'), ('data_error', 'Error en los datos')], max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.order')),
            ],
        ),
    ]
