# Generated by Django 4.2.2 on 2024-04-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0033_alter_order_storage_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
