# Generated by Django 4.2.2 on 2024-04-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0034_alter_order_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeclinereazon',
            name='decline_reazon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
