# Generated by Django 4.2.2 on 2024-04-16 11:37
from django.db import migrations


RMap = {
    "no_money": "No tiene dinero",
    "price": "No está de acuerdo con el precio",
    "later": "Lo va a hacer más adelante",
    "wait": "No puede esperar",
    "conditions": "No está de acuerdo con los terminos",
    "data_error": "Error en los datos",
}


def actualizar_valores(apps, schema_editor):
    OrderDeclineReazon = apps.get_model("utils", "OrderDeclineReazon")
    for odr in OrderDeclineReazon.objects.all():
        if str(odr.decline_reazon) in RMap:
            odr.decline_reazon = RMap[str(odr.decline_reazon)]
            odr.save()


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0035_alter_orderdeclinereazon_decline_reazon"),
    ]

    operations = [migrations.RunPython(actualizar_valores)]
