# Generated by Django 4.2.2 on 2024-04-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0036_auto_decline_reazon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='position_date',
            field=models.DateField(null=True),
        ),
    ]
