# Generated by Django 4.2.2 on 2024-04-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0037_order_position_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='position_date',
            field=models.DateTimeField(null=True),
        ),
    ]
