# Generated by Django 4.2.2 on 2024-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0039_order_processing_user_order_terminated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parts_sale',
            field=models.BooleanField(default=False),
        ),
    ]
