# Generated by Django 4.2.2 on 2024-04-23 13:02
from django.db import migrations
from django.db.models import Q

from utils.models import Order


def fix_quotation_parts_orders(app, schema):
    # Quotation type fix
    orders = Order.objects.filter(
        ~Q(type="sell"),
        quotation=True,
    )
    for o in orders:
        o.type = "sell"
        o.save()

    # Parts ctl and type fix
    orders = Order.objects.filter(
        concept="Parts' sale",
    )
    for o in orders:
        o.type = "sell"
        o.parts_sale = True
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0040_order_parts_sale"),
    ]

    operations = [migrations.RunPython(fix_quotation_parts_orders)]
