# Generated by Django 4.2.2 on 2023-12-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tolls", "0002_tolldue_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tolldue",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
