# Generated by Django 4.2.2 on 2024-06-13 19:37
from django.db import migrations

from tolls.forms import TollDue


def init_after_end(apps, schema):
    tolls = TollDue.objects.exclude(contract=None).exclude(contract__ended_date=None)
    for t in tolls:
        if t.contract.ended_date < t.created_date:
            t.after_end = True
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tolls", "0004_tolldue_after_end"),
    ]

    operations = [migrations.RunPython(init_after_end)]
